### ISSUE TITLE
Error expiring plans with Celery 5.0.0

### ISSUE THREAD

**Issue by PetrDlouhy** [django-getpaid/django-plans#120]
I have got following import error with Celery 5.0.0:
```
  File "/app/blenderhub/apps/accounts/management/commands/expire_plans.py", line 2, in <module>
    from plans import tasks
  File "/app/src/django-plans/plans/tasks.py", line 4, in <module>
    from celery.task.base import periodic_task
ModuleNotFoundError: No module named 'celery.task'
```

Also, the Celery dependency should be optional, as `django-plans` can now be used with management command instead of Celery.

**Comment by nmmapper** [comment]
Am facing this also!

**Comment by nmmapper** [comment]
If any one encounters this kind of error, the issue is quick easy to fix

1) Solution 1 Disable autodiscover_tasks

`#app.autodiscover_tasks(related_name="tasks")`

This will ensure that celery does not scan for apps to find task to added, in this case the buggy plan.tasks won't be added also, because celery is not scanning for tasks in installed apps. 

Though ensure that you set this variable

`CELERY_IMPORTS = [ your tasks for celery to import ] `

2) Solution 2 Define which apps should be auto discored.

```
APPS_TO_FIND_TASKS = [ "app1", "app2, "app3", "app4"] # This can be handy if you have other thirdparty apps that you want to be automatically auto-discovered while rejecting others.

app.autodiscover_tasks(packages=APPS_TO_FIND_TASKS, related_name="tasks")
```

**Comment by PetrDlouhy** [comment]
The Celery dependency should be removed now.
